---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"  # nightly build
# command to install dependencies
install:
  - python setup.py -q install
# command to run tests
script:
  - python -m pytest
