---
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - python setup.py -q install
  - python -m pip install -q tensorflow keras
# command to run tests
script:
  - python -m pytest
